version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
worckflows:
  build:
    jobs:
      - cypress/install

            - cypress/run:
                requires:
                  - cypress/install
                  - build: 'npm run build' # run a custom app build step
                record: true
                group: all tests
                start: npm start